language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
env:
  - IMAGE_DRIVER=imagick
  - IMAGE_DRIVER=im
matrix: 
  allow_failures: 
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
before_script:
  - sh .travis.install.sh
script: 
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --verbose; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover /tmp/coverage/coverage.xml; fi;'
notififation:   
  on_success: never
  on_failure: always
